server:
  port: 5000

upload:
  provider: "local"          # local | s3 | drive
  folder: "uploads"
  # s3:
  #   bucket: "${S3_BUCKET}"
  #   region: "${S3_REGION}"
  #   accessKeyId: "${S3_ACCESS_KEY_ID}"
  #   secretAccessKey: "${S3_SECRET_ACCESS_KEY}"
  # drive:
  #   credentialsPath: "${DRIVE_CREDENTIALS_PATH}"
  #   folderId: "${DRIVE_FOLDER_ID}"
  #   api_url: "https://www.googleapis.com/drive/v3/files"

ocr:
  provider: "free_ocr"
  api_key: "${FREE_OCR_API_KEY}"
  endpoint: "https://api.ocr.space/parse/image"

llm:
  provider: "gemini"
  api_key: "${LLM_KEY}"
  llm_model: "gemini-2.5-flash"
  prompt_template: |
    You are a receipt/invoice parsing AI.

    OCR Input:
    {{text}}

    Rules:
    - Do NOT guess, normalize, or hallucinate data.
    - Output JSON ONLY (valid JSON, no markdown):
      {
        "document_type": string,
        "vendor": { "name": string, "address": string, "phone": string },
        "bill_to": { "name": string, "address": string, "phone": string },
        "invoice": { "number": string, "date": string },
        "payment": string,
        "items": [ { "description": string, "quantity": string, "unit_price": string, "total": string } ],
        "subtotal": string,
        "tax": string,
        "total": string,
        "po_number": string,
        "notes": string,
        "raw_ocr_text": string
      }

